# Generated by Django 5.2.16 on 2026-07-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_current_organization'),
    ]

    operations = [
    ]
