# Generated by Django 5.2.16 on 2026-07-29 11:34

import django.db.models.deletion
import reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('trips_summary', 'Trips Summary'), ('fleet_utilization', 'Fleet Utilization'), ('driver_performance', 'Driver Performance'), ('delivery_analysis', 'Delivery Analysis'), ('revenue_summary', 'Revenue Summary'), ('cost_analysis', 'Cost Analysis'), ('fuel_consumption', 'Fuel Consumption'), ('maintenance_costs', 'Maintenance Costs'), ('on_time_delivery', 'On-Time Delivery'), ('safety_incidents', 'Safety Incidents'), ('customer_satisfaction', 'Customer Satisfaction'), ('efficiency_metrics', 'Efficiency Metrics'), ('document_compliance', 'Document Compliance'), ('expiry_tracking', 'Expiry Tracking'), ('verification_status', 'Verification Status')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(blank=True, help_text='user, vehicle, organization, etc.', max_length=20)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=reports.models.report_upload_path)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_format', models.CharField(default='pdf', help_text='pdf, csv, xlsx', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_generated', models.DateTimeField(auto_now=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Report generation parameters')),
                ('row_count', models.PositiveIntegerField(blank=True, help_text='Number of data rows', null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', '-created_at'], name='reports_rep_report__6e1fe1_idx'), models.Index(fields=['status', '-created_at'], name='reports_rep_status_7dd5e5_idx'), models.Index(fields=['entity_type', 'entity_id'], name='reports_rep_entity__eef0d7_idx'), models.Index(fields=['generated_by', '-created_at'], name='reports_rep_generat_ef0442_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('trips_summary', 'Trips Summary'), ('fleet_utilization', 'Fleet Utilization'), ('driver_performance', 'Driver Performance'), ('delivery_analysis', 'Delivery Analysis'), ('revenue_summary', 'Revenue Summary'), ('cost_analysis', 'Cost Analysis'), ('fuel_consumption', 'Fuel Consumption'), ('maintenance_costs', 'Maintenance Costs'), ('on_time_delivery', 'On-Time Delivery'), ('safety_incidents', 'Safety Incidents'), ('customer_satisfaction', 'Customer Satisfaction'), ('efficiency_metrics', 'Efficiency Metrics'), ('document_compliance', 'Document Compliance'), ('expiry_tracking', 'Expiry Tracking'), ('verification_status', 'Verification Status')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recipients', models.JSONField(default=list, help_text='List of user IDs to email report to')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run'],
                'indexes': [models.Index(fields=['next_run', 'is_active'], name='reports_rep_next_ru_940c4f_idx'), models.Index(fields=['frequency'], name='reports_rep_frequen_1e97ea_idx')],
            },
        ),
    ]
