# Generated by Django 5.2.16 on 2026-07-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_fix_notification_nullable_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_05b4bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_878a13_idx',
        ),
    ]
