# Generated by Django 5.2.16 on 2026-08-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('alert', 'Alert'), ('success', 'Success'), ('info', 'Info'), ('warning', 'Warning'), ('shipment_status', 'Shipment Status'), ('dispatch_assignment', 'Dispatch Assignment'), ('gps_alert', 'GPS Alert'), ('maintenance_due', 'Maintenance Due'), ('fuel_anomaly', 'Fuel Anomaly'), ('password_reset', 'Password Reset'), ('account_verification', 'Account Verification'), ('document_expiry', 'Document Expiry'), ('admin_custom', 'Admin Custom')], default='info', max_length=30),
        ),
    ]
