# Generated by Django 5.2.16 on 2026-08-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='in_app_admin_custom',
            field=models.BooleanField(default=True),
        ),
    ]
