# Generated by Django 6.0.7 on 2026-07-27 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('dispatched', 'Dispatched'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=10)),
                ('sequence', models.PositiveIntegerField(help_text='Order of this stop within the trip')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stops', to='orders.shipment')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='dispatch.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence'],
                'unique_together': {('trip', 'shipment', 'stop_type')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='shipments',
            field=models.ManyToManyField(related_name='trips', through='dispatch.TripStop', to='orders.shipment'),
        ),
    ]
