# Generated by Django 5.2.16 on 2026-08-04 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
        ('fleet', '0003_vehicledocument_vehicleinspection_and_more'),
        ('orders', '0003_shipment_driver_shipment_vehicle'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='trip',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['organization'], name='dispatch_tr_organiz_e1990d_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='dispatch_tr_status_8e22b9_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['scheduled_start'], name='dispatch_tr_schedul_531001_idx'),
        ),
    ]
