# Generated by Django 5.2.16 on 2026-08-04 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_alter_trip_options_trip_organization_and_more'),
        ('fleet', '0003_vehicledocument_vehicleinspection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle'),
        ),
    ]
