# Generated by Django 5.2.16 on 2026-08-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_alter_trip_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='actual_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
