# Generated by Django 5.2.16 on 2026-08-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_alter_trip_actual_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
