# Generated by Django 6.0.7 on 2026-07-27 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_contact_phone', models.CharField(blank=True, max_length=20)),
                ('pickup_window_start', models.DateTimeField(blank=True, null=True)),
                ('pickup_window_end', models.DateTimeField(blank=True, null=True)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_contact_phone', models.CharField(blank=True, max_length=20)),
                ('cargo_description', models.CharField(blank=True, max_length=255)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('urgent', 'Urgent')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.customer')),
            ],
        ),
    ]
