# Generated by Django 5.2.16 on 2026-07-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicledocument_vehicleinspection_and_more'),
        ('orders', '0002_customer_organization_shipment_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to='fleet.vehicle'),
        ),
    ]
