# Generated by Django 5.2.16 on 2026-07-27 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('vehicles', 'Vehicles'), ('drivers', 'Drivers'), ('dispatch', 'Dispatch'), ('tracking', 'Tracking'), ('orders', 'Orders'), ('maintenance', 'Maintenance'), ('fuel', 'Fuel'), ('inventory', 'Inventory'), ('compliance', 'Compliance'), ('incidents', 'Incidents'), ('financial', 'Financial'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.ManyToManyField(related_name='permission_groups', to='auth.permission')),
            ],
            options={
                'ordering': ['module', 'name'],
                'unique_together': {('name', 'module')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('dispatcher', 'Dispatcher'), ('driver', 'Driver'), ('customer', 'Customer'), ('viewer', 'Viewer')], max_length=20)),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('vehicles', 'Vehicles'), ('drivers', 'Drivers'), ('dispatch', 'Dispatch'), ('tracking', 'Tracking'), ('orders', 'Orders'), ('maintenance', 'Maintenance'), ('fuel', 'Fuel'), ('inventory', 'Inventory'), ('compliance', 'Compliance'), ('incidents', 'Incidents'), ('financial', 'Financial'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=20)),
                ('access_level', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('edit', 'Edit'), ('full', 'Full Control')], default='none', max_length=10)),
                ('custom_permissions', models.ManyToManyField(blank=True, related_name='custom_role_permissions', to='auth.permission')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'role', 'module'],
                'unique_together': {('organization', 'role', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='organizations.organization')),
                ('permissions', models.ManyToManyField(related_name='user_custom_permissions', to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
