# Generated by Django 5.2.16 on 2026-07-28 18:09

from django.db import migrations


def seed_default_role_permissions(apps, schema_editor):
    """Seed default role permissions for each organization."""
    RolePermission = apps.get_model('permissions', 'RolePermission')
    Organization = apps.get_model('organizations', 'Organization')
    
    # Define default permissions for each role
    default_permissions = {
        'admin': {
            'vehicles': 'FULL',
            'dispatch': 'FULL',
            'orders': 'FULL',
            'tracking': 'FULL',
            'routes': 'FULL',
            'fuel': 'FULL',
            'dashboard': 'FULL',
            'settings': 'FULL',
        },
        'dispatcher': {
            'vehicles': 'EDIT',
            'dispatch': 'FULL',
            'orders': 'EDIT',
            'tracking': 'EDIT',
            'routes': 'VIEW',
            'fuel': 'VIEW',
            'dashboard': 'VIEW',
            'settings': 'VIEW',
        },
        'driver': {
            'vehicles': 'VIEW',
            'dispatch': 'VIEW',
            'orders': 'VIEW',
            'tracking': 'VIEW',
            'routes': 'VIEW',
            'fuel': 'VIEW',
            'dashboard': 'VIEW',
            'settings': 'NONE',
        },
        'customer': {
            'vehicles': 'NONE',
            'dispatch': 'NONE',
            'orders': 'VIEW',
            'tracking': 'VIEW',
            'routes': 'NONE',
            'fuel': 'VIEW',
            'dashboard': 'VIEW',
            'settings': 'NONE',
        },
    }
    
    # Get all organizations
    organizations = Organization.objects.all()
    
    # Create default permissions for each organization
    for org in organizations:
        for role, modules in default_permissions.items():
            for module, access_level in modules.items():
                RolePermission.objects.get_or_create(
                    organization=org,
                    role=role,
                    module=module,
                    defaults={'access_level': access_level}
                )


def reverse_seed_default_role_permissions(apps, schema_editor):
    """Reverse the seeding by deleting all role permissions."""
    RolePermission = apps.get_model('permissions', 'RolePermission')
    RolePermission.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_default_role_permissions, reverse_seed_default_role_permissions),
    ]
