# Generated by Django 5.2.16 on 2026-07-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_seed_default_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('vehicles', 'Vehicles'), ('drivers', 'Drivers'), ('dispatch', 'Dispatch'), ('tracking', 'Tracking'), ('orders', 'Orders'), ('routes', 'Routes'), ('maintenance', 'Maintenance'), ('fuel', 'Fuel'), ('inventory', 'Inventory'), ('compliance', 'Compliance'), ('incidents', 'Incidents'), ('financial', 'Financial'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('vehicles', 'Vehicles'), ('drivers', 'Drivers'), ('dispatch', 'Dispatch'), ('tracking', 'Tracking'), ('orders', 'Orders'), ('routes', 'Routes'), ('maintenance', 'Maintenance'), ('fuel', 'Fuel'), ('inventory', 'Inventory'), ('compliance', 'Compliance'), ('incidents', 'Incidents'), ('financial', 'Financial'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=20),
        ),
    ]
