# Generated by Django 5.2.16 on 2026-07-28 18:29

from django.db import migrations


def update_customer_fuel_permissions(apps, schema_editor):
    """Update customer role to have VIEW access to fuel module."""
    RolePermission = apps.get_model('permissions', 'RolePermission')
    Organization = apps.get_model('organizations', 'Organization')
    
    # Update customer permissions for fuel module
    organizations = Organization.objects.all()
    for org in organizations:
        RolePermission.objects.filter(
            organization=org,
            role='customer',
            module='fuel'
        ).update(access_level='view')


def reverse_update_customer_fuel_permissions(apps, schema_editor):
    """Reverse the customer fuel permissions update."""
    RolePermission = apps.get_model('permissions', 'RolePermission')
    Organization = apps.get_model('organizations', 'Organization')
    
    # Revert customer permissions for fuel module
    organizations = Organization.objects.all()
    for org in organizations:
        RolePermission.objects.filter(
            organization=org,
            role='customer',
            module='fuel'
        ).update(access_level='none')


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_alter_permissiongroup_module_and_more'),
    ]

    operations = [
        migrations.RunPython(update_customer_fuel_permissions, reverse_update_customer_fuel_permissions),
    ]
