# Generated by Django 5.2.16 on 2026-08-04 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_settings', to='organizations.organization'),
        ),
    ]
