# Generated by Django 5.2.16 on 2026-07-27 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicledocument_vehicleinspection_and_more'),
        ('orders', '0002_customer_organization_shipment_organization_and_more'),
        ('organizations', '0001_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('geofence_type', models.CharField(choices=[('delivery_zone', 'Delivery Zone'), ('restricted_area', 'Restricted Area'), ('route_corridor', 'Route Corridor'), ('warehouse', 'Warehouse')], default='delivery_zone', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('boundary_type', models.CharField(default='polygon', help_text='polygon, circle', max_length=20)),
                ('coordinates', models.JSONField(default=list, help_text='Array of [lat, lng] pairs')),
                ('radius_m', models.PositiveIntegerField(blank=True, help_text='For circle geofences', null=True)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GPSAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('delay', 'Delivery Delay'), ('breakdown', 'Vehicle Breakdown'), ('accident', 'Accident'), ('traffic', 'Traffic Issue'), ('weather', 'Weather Issue'), ('customer_issue', 'Customer Issue'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('trip_id', models.UUIDField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vehiclelocationping',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehiclelocationping',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_updates', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='vehiclelocationping',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by dispatcher'),
        ),
        migrations.AddField(
            model_name='vehiclelocationping',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiclelocationping',
            name='odometer_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocationping',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='vehiclelocationping',
            name='status_update',
            field=models.CharField(blank=True, help_text='on_trip, break, available, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiclelocationping',
            name='trip_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocationping',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocationping',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='vehiclelocationping',
            index=models.Index(fields=['driver', '-recorded_at'], name='tracking_ve_driver__706261_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelocationping',
            index=models.Index(fields=['organization', '-recorded_at'], name='tracking_ve_organiz_093850_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelocationping',
            index=models.Index(fields=['recorded_at'], name='tracking_ve_recorde_62daa7_idx'),
        ),
        migrations.AddField(
            model_name='geofence',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='geofence',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='geofences', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='gpsalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_gps_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gpsalert',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_alerts', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='gpsalert',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_alerts', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='gpsalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_gps_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gpsalert',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_tracking_alerts', to='orders.shipment'),
        ),
        migrations.AddField(
            model_name='gpsalert',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_alerts', to='fleet.vehicle'),
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['organization', 'status'], name='tracking_ge_organiz_58eb34_idx'),
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['organization', 'geofence_type'], name='tracking_ge_organiz_41ed0f_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsalert',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='tracking_gp_organiz_caddfb_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsalert',
            index=models.Index(fields=['vehicle', '-created_at'], name='tracking_gp_vehicle_78066c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsalert',
            index=models.Index(fields=['alert_type', '-created_at'], name='tracking_gp_alert_t_9d3af7_idx'),
        ),
    ]
