# Generated by Django 5.2.16 on 2026-08-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_geofence_gpsalert_vehiclelocationping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelocationping',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='vehiclelocationping',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, blank=True),
        ),
    ]
