# Generated by Django 5.2.16 on 2026-08-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_fix_location_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsalert',
            name='alert_type',
            field=models.CharField(choices=[('delay', 'Delivery Delay'), ('breakdown', 'Vehicle Breakdown'), ('accident', 'Accident'), ('traffic', 'Traffic Issue'), ('weather', 'Weather Issue'), ('customer_issue', 'Customer Issue'), ('sos', 'SOS Emergency'), ('other', 'Other')], max_length=20),
        ),
    ]
