# Generated by Django 5.2.16 on 2026-08-06 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicledocument_vehicleinspection_and_more'),
        ('tracking', '0004_alter_gpsalert_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsalert',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_alerts', to='fleet.vehicle'),
        ),
    ]
