# Generated by Django 5.2.16 on 2026-07-27 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['organization', 'license_number'], name='fleet_drive_organiz_84f38e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['organization', 'plate_number'], name='fleet_vehic_organiz_800c0a_idx'),
        ),
    ]
