# Generated by Django 5.2.16 on 2026-07-27 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_driver_organization_vehicle_organization_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('registration', 'Registration'), ('insurance', 'Insurance'), ('inspection', 'Inspection'), ('permit', 'Permit'), ('maintenance', 'Maintenance Record'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('expiring_soon', 'Expiring Soon'), ('pending', 'Pending')], default='valid', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('reminder_days_before', models.PositiveIntegerField(default=30)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_type', models.CharField(choices=[('pre_trip', 'Pre-Trip'), ('post_trip', 'Post-Trip'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='daily', max_length=20)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('conditional', 'Conditional')], default='passed', max_length=20)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('odometer_reading', models.PositiveIntegerField(blank=True, null=True)),
                ('check_results', models.JSONField(default=dict, help_text='Detailed inspection checklist results')),
                ('issues_found', models.TextField(blank=True)),
                ('issues_resolved', models.TextField(blank=True)),
                ('immediate_actions', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('inspector_signature', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='service_date',
        ),
        migrations.AddField(
            model_name='driver',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of driver certifications'),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractor', 'Contractor'), ('temporary', 'Temporary')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_issuing_authority',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='medical_exam_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='on_time_performance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='On-time delivery percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='safety_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Safety score out of 10', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_trips',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='labor_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.CharField(choices=[('routine', 'Routine Service'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('emergency', 'Emergency Repair'), ('upgrade', 'Upgrade')], default='routine', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='odometer_at_service',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='parts_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='performed_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='service_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='service_provider',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='work_performed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity_volume_m3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_odometer',
            field=models.PositiveIntegerField(default=0, help_text='Current odometer reading in km'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lease_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='length_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_service_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('leased', 'Leased'), ('rented', 'Rented')], default='owned', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='width_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('off_duty', 'Off Duty'), ('on_leave', 'On Leave'), ('suspended', 'Suspended')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service'), ('retired', 'Retired')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['organization', 'status'], name='fleet_drive_organiz_729866_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['organization', 'employment_type'], name='fleet_drive_organiz_72dc66_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['vehicle', '-created_at'], name='fleet_maint_vehicle_f5b9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['vehicle', 'status'], name='fleet_maint_vehicle_f43fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['organization', 'status'], name='fleet_vehic_organiz_12877b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['organization', 'vehicle_type'], name='fleet_vehic_organiz_9b0027_idx'),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='fleet.vehicle'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['vehicle', 'document_type'], name='fleet_vehic_vehicle_89df13_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['vehicle', 'expiry_date'], name='fleet_vehic_vehicle_8aaa63_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['expiry_date'], name='fleet_vehic_expiry__020259_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['vehicle', '-inspection_date'], name='fleet_vehic_vehicle_640ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['driver', '-inspection_date'], name='fleet_vehic_driver__15d511_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['inspection_type', '-inspection_date'], name='fleet_vehic_inspect_086e6e_idx'),
        ),
    ]
