# Generated by Django 5.2.16 on 2026-07-27 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0001_initial'),
        ('fleet', '0002_driver_organization_vehicle_organization_and_more'),
        ('orders', '0002_customer_organization_shipment_organization_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('threshold', 'Threshold Breach'), ('anomaly', 'Anomaly Detected'), ('system', 'System Event'), ('business', 'Business Event')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_alerts', to='organizations.organization')),
                ('related_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='fleet.driver')),
                ('related_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='orders.shipment')),
                ('related_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='dispatch.trip')),
                ('related_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='fleet.vehicle')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status', '-created_at'], name='dashboard_d_organiz_ee4e69_idx'), models.Index(fields=['organization', 'severity', '-created_at'], name='dashboard_d_organiz_87ba98_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('metric_card', 'Metric Card'), ('chart', 'Chart'), ('table', 'Table'), ('map', 'Map'), ('alert', 'Alert'), ('activity_feed', 'Activity Feed')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('chart_type', models.CharField(blank=True, choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('area', 'Area Chart'), ('donut', 'Donut Chart')], max_length=20)),
                ('data_source', models.CharField(help_text='API endpoint or data source', max_length=100)),
                ('data_query', models.JSONField(blank=True, default=dict, help_text='Query parameters for data source')),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=4)),
                ('height', models.PositiveIntegerField(default=3)),
                ('refresh_interval', models.PositiveIntegerField(default=300, help_text='Refresh interval in seconds')),
                ('is_visible', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Widget-specific configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='organizations.organization')),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
                'indexes': [models.Index(fields=['organization', 'position_x', 'position_y'], name='dashboard_d_organiz_f03da1_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metric_unit', models.CharField(blank=True, max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('dimensions', models.JSONField(default=dict, help_text='Additional dimensions (vehicle, driver, etc.)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='organizations.organization')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['organization', 'metric_name', '-period_start'], name='dashboard_m_organiz_15a44c_idx'), models.Index(fields=['organization', '-recorded_at'], name='dashboard_m_organiz_481cf3_idx')],
                'unique_together': {('organization', 'metric_name', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('summary', 'Summary Report'), ('detailed', 'Detailed Report'), ('financial', 'Financial Report'), ('operational', 'Operational Report'), ('custom', 'Custom Report')], max_length=20)),
                ('data_sources', models.JSONField(default=list, help_text='List of data sources and queries')),
                ('filters', models.JSONField(default=dict, help_text='Report filters and parameters')),
                ('group_by', models.JSONField(default=list, help_text='Grouping and aggregation rules')),
                ('schedule_type', models.CharField(blank=True, help_text='daily, weekly, monthly, etc.', max_length=20)),
                ('schedule_config', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Visible to all organization members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='organizations.organization')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='dashboard_s_organiz_d49187_idx'), models.Index(fields=['organization', 'report_type'], name='dashboard_s_organiz_a1ee89_idx')],
            },
        ),
    ]
