# Generated by Django 5.2.16 on 2026-07-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('dispatch', '0001_initial'),
        ('fleet', '0003_vehicledocument_vehicleinspection_and_more'),
        ('orders', '0002_customer_organization_shipment_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardalert',
            name='related_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_alerts', to='fleet.driver'),
        ),
        migrations.AlterField(
            model_name='dashboardalert',
            name='related_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_alerts', to='orders.shipment'),
        ),
        migrations.AlterField(
            model_name='dashboardalert',
            name='related_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_alerts', to='dispatch.trip'),
        ),
        migrations.AlterField(
            model_name='dashboardalert',
            name='related_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_alerts', to='fleet.vehicle'),
        ),
    ]
