# Generated by Django 5.2.16 on 2026-07-27 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0003_vehicledocument_vehicleinspection_and_more'),
        ('orders', '0002_customer_organization_shipment_organization_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('route_type', models.CharField(choices=[('delivery', 'Delivery Route'), ('pickup', 'Pickup Route'), ('mixed', 'Mixed Pickup/Delivery'), ('transfer', 'Transfer/Relocation')], default='delivery', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('optimization_level', models.CharField(choices=[('none', 'None (Manual Order)'), ('basic', 'Basic Optimization'), ('advanced', 'Advanced Optimization'), ('real_time', 'Real-time Optimization')], default='none', max_length=20)),
                ('planned_start_time', models.DateTimeField(blank=True, null=True)),
                ('planned_end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='fleet.driver')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='organizations.organization')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-planned_start_time'],
            },
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('nearest_neighbor', 'Nearest Neighbor'), ('genetic', 'Genetic Algorithm'), ('tabu_search', 'Tabu Search'), ('simulated_annealing', 'Simulated Annealing'), ('google_or', 'Google OR-Tools')], default='nearest_neighbor', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('max_stops_per_route', models.PositiveIntegerField(default=10)),
                ('max_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time_window_start', models.TimeField(blank=True, null=True)),
                ('time_window_end', models.TimeField(blank=True, null=True)),
                ('original_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('optimized_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_savings_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_savings_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('original_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('optimized_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_savings_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_savings_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('optimized_stop_order', models.JSONField(blank=True, default=list)),
                ('optimization_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_optimizations', to='organizations.organization')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='routes.route')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('fuel', 'Fuel Stop'), ('rest', 'Rest Break'), ('warehouse', 'Warehouse'), ('custom', 'Custom')], default='delivery', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approaching', 'Approaching'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sequence_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('planned_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('planned_departure_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('distance_from_previous_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_travel_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('requires_signature', models.BooleanField(default=False)),
                ('requires_photo', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_stops', to='orders.shipment')),
            ],
            options={
                'ordering': ['route', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='RouteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('daily', 'Daily Route'), ('weekly', 'Weekly Route'), ('zone', 'Zone-based Route'), ('customer', 'Customer-specific'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('default_vehicle_type', models.CharField(blank=True, max_length=50)),
                ('max_stops', models.PositiveIntegerField(default=10)),
                ('typical_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('typical_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('zone_coordinates', models.JSONField(blank=True, default=list, help_text='Polygon coordinates for zone')),
                ('zone_center_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('zone_center_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('zone_radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('default_stop_types', models.JSONField(blank=True, default=list)),
                ('time_window_start', models.TimeField(blank=True, null=True)),
                ('time_window_end', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_templates', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['organization', 'status'], name='routes_rout_organiz_8d9ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['organization', 'planned_start_time'], name='routes_rout_organiz_b0bb5d_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['vehicle', 'planned_start_time'], name='routes_rout_vehicle_6e12b2_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['driver', 'planned_start_time'], name='routes_rout_driver__264d83_idx'),
        ),
        migrations.AddIndex(
            model_name='routeoptimization',
            index=models.Index(fields=['organization', 'status'], name='routes_rout_organiz_801452_idx'),
        ),
        migrations.AddIndex(
            model_name='routeoptimization',
            index=models.Index(fields=['route', '-created_at'], name='routes_rout_route_i_94139c_idx'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['route', 'sequence_number'], name='routes_rout_route_i_5874c1_idx'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['shipment'], name='routes_rout_shipmen_d2d41c_idx'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['status'], name='routes_rout_status_d42797_idx'),
        ),
        migrations.AddIndex(
            model_name='routetemplate',
            index=models.Index(fields=['organization', 'is_active'], name='routes_rout_organiz_f90975_idx'),
        ),
        migrations.AddIndex(
            model_name='routetemplate',
            index=models.Index(fields=['template_type'], name='routes_rout_templat_5d0297_idx'),
        ),
    ]
