# Generated by Django 5.2.16 on 2026-07-29 11:17

import django.core.validators
import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('vehicle', 'Vehicle'), ('organization', 'Organization')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('kra_pin', 'KRA PIN'), ('kra_certificate', 'KRA Certificate'), ('driving_license', 'Driving License'), ('profile_photo', 'Profile Photo'), ('certificate_of_good_conduct', 'Certificate of Good Conduct'), ('passport', 'Passport'), ('medical_certificate', 'Medical Certificate'), ('insurance', 'Insurance'), ('registration', 'Registration'), ('number_plate', 'Number Plate'), ('inspection_certificate', 'Inspection Certificate'), ('road_worthiness', 'Road Worthiness Certificate'), ('logbook', 'Logbook'), ('contract', 'Contract'), ('nda', 'Non-Disclosure Agreement'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('expiring_soon', 'Expiring Soon'), ('pending', 'Pending Verification'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_number', models.CharField(blank=True, help_text='Document number/ID if applicable', max_length=100)),
                ('issuing_authority', models.CharField(blank=True, help_text='Issuing authority/organization', max_length=200)),
                ('issue_date', models.DateField(blank=True, help_text='Date when document was issued', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Date when document expires', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_url', models.URLField(blank=True, help_text='External URL if file is stored elsewhere')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('reminder_days_before', models.PositiveIntegerField(default=30, help_text='Days before expiry to send reminder')),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional document metadata')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('vehicle', 'Vehicle'), ('organization', 'Organization')], max_length=20)),
                ('user_role', models.CharField(choices=[('driver', 'Driver'), ('dispatcher', 'Dispatcher'), ('admin', 'Admin'), ('customer', 'Customer'), ('all', 'All Roles')], default='all', max_length=20)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('kra_pin', 'KRA PIN'), ('kra_certificate', 'KRA Certificate'), ('driving_license', 'Driving License'), ('profile_photo', 'Profile Photo'), ('certificate_of_good_conduct', 'Certificate of Good Conduct'), ('passport', 'Passport'), ('medical_certificate', 'Medical Certificate'), ('insurance', 'Insurance'), ('registration', 'Registration'), ('number_plate', 'Number Plate'), ('inspection_certificate', 'Inspection Certificate'), ('road_worthiness', 'Road Worthiness Certificate'), ('logbook', 'Logbook'), ('contract', 'Contract'), ('nda', 'Non-Disclosure Agreement'), ('other', 'Other')], max_length=50)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this document is mandatory')),
                ('is_expirable', models.BooleanField(default=True, help_text='Whether this document has an expiry date')),
                ('default_reminder_days', models.PositiveIntegerField(default=30, help_text='Default reminder days before expiry')),
                ('description', models.TextField(blank=True, help_text='Description of why this document is required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['entity_type', 'user_role', 'document_type'],
                'indexes': [models.Index(fields=['entity_type', 'user_role'], name='documents_d_entity__264425_idx'), models.Index(fields=['document_type'], name='documents_d_documen_d51823_idx')],
                'unique_together': {('entity_type', 'user_role', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='DocumentVerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('uploaded', 'Uploaded'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('updated', 'Updated'), ('expired', 'Expired'), ('reminder_sent', 'Reminder Sent')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Record of changes made')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='documents.document')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_verification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['entity_type', 'entity_id'], name='documents_d_entity__bec8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiry_date'], name='documents_d_expiry__1d702a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_verified'], name='documents_d_is_veri_00d375_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['entity_type', 'document_type', 'expiry_date'], name='documents_d_entity__a2b666_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number__isnull', False)), fields=('entity_type', 'entity_id', 'document_type', 'document_number'), name='unique_document_per_entity', violation_error_message='A document with this number already exists for this entity.'),
        ),
        migrations.AddIndex(
            model_name='documentverificationlog',
            index=models.Index(fields=['document', '-created_at'], name='documents_d_documen_14ab78_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverificationlog',
            index=models.Index(fields=['action', '-created_at'], name='documents_d_action_fbacd7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverificationlog',
            index=models.Index(fields=['performed_by', '-created_at'], name='documents_d_perform_4e49c6_idx'),
        ),
    ]
