# Generated by Django 5.2.16 on 2026-07-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='entity_id',
            field=models.CharField(max_length=36),
        ),
    ]
