# Generated by Django 5.2.16 on 2026-07-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_entity_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_document_per_entity',
        ),
    ]
