# Generated by Django 5.2.16 on 2026-07-27 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_driver_organization_vehicle_organization_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('card_type', models.CharField(choices=[('fleet', 'Fleet Card'), ('credit', 'Credit Card'), ('debit', 'Debit Card'), ('prepaid', 'Prepaid Card')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('lost', 'Lost'), ('expired', 'Expired')], default='active', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('cardholder_name', models.CharField(blank=True, max_length=200)),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weekly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('pin', models.CharField(blank=True, help_text='Encrypted PIN', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_cards', to='organizations.organization')),
                ('vehicles', models.ManyToManyField(blank=True, related_name='fuel_cards', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['card_number'],
            },
        ),
        migrations.CreateModel(
            name='FuelAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('high_consumption', 'High Consumption'), ('low_fuel', 'Low Fuel'), ('card_expiry', 'Card Expiry'), ('price_spike', 'Price Spike'), ('fraud_suspected', 'Fraud Suspected')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_alerts', to='organizations.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_alerts', to='fleet.vehicle')),
                ('fuel_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fuel.fuelcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fuel_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_consumption_l_per_100km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avg_cost_per_km', models.DecimalField(decimal_places=3, max_digits=6)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_consumption', to='organizations.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_consumption_records', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('gas', 'Gas')], max_length=20)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('station_name', models.CharField(blank=True, max_length=200)),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_liter', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('odometer_reading', models.PositiveIntegerField(help_text='Vehicle odometer at time of fueling')),
                ('full_tank', models.BooleanField(default=False, help_text='Was the tank filled completely?')),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to='fleet.driver')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_transactions', to='organizations.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_transactions', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='fuelcard',
            index=models.Index(fields=['organization', 'card_number'], name='fuel_fuelca_organiz_74910a_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelalert',
            index=models.Index(fields=['organization', 'is_resolved', '-created_at'], name='fuel_fuelal_organiz_22c031_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelalert',
            index=models.Index(fields=['organization', 'vehicle', '-created_at'], name='fuel_fuelal_organiz_c80517_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelconsumption',
            index=models.Index(fields=['organization', 'vehicle', '-period_start'], name='fuel_fuelco_organiz_88f70b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fuelconsumption',
            unique_together={('vehicle', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['organization', 'vehicle', '-date'], name='fuel_fueltr_organiz_4bee34_idx'),
        ),
        migrations.AddIndex(
            model_name='fueltransaction',
            index=models.Index(fields=['organization', '-date'], name='fuel_fueltr_organiz_e7a151_idx'),
        ),
    ]
