# Generated by Django 5.2.16 on 2026-07-28 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelalert',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_alerts', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='fuelcard',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_cards', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_consumption', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_transactions', to='organizations.organization'),
        ),
    ]
